### ISSUE TITLE
Provide a Unix manual page

### ISSUE THREAD

**Issue by lindig** [gasche/manual-ocamlbuild#16]
OCamlbuild is part of the OCaml distribution that in general provides Unix manual pages for its command line tools. OCamlbuild provides too much functionality to document it exhaustively in a manual page but a short page that explains its purpose and points to the manual would be appropriate. I'm happy to write such a manual page if there is consensus that this is a good idea. As an alternative, we could try to automatically convert the markdown documentation into a manual page but I am not convinced that this is worth the effort.

**Comment by gasche** [comment]
Yes, it is a good idea. For now the best place where to put such a manpage would be in the `man/` subdirectory of the compiler distribution, along with the manpages with the other tool. If you write one (feel free to take inspiration from the others), you should thus send it as a pull request against the [ocaml](https://github.com/ocaml/ocaml/) repository. I fully agree that we want something somewhat concise, rather than the automatic conversion of a verbose documentation.

**Comment by lindig** [comment]
Actually, there is a manual page: [ocamlbuild.1](https://github.com/ocaml/ocaml/blob/trunk/ocamlbuild/man/ocamlbuild.1) but at least in my installation it is not installed.

**Comment by gasche** [comment]
Heh, so this was inadequate advice... I think we can close this particular issue now. I'll investigate the manpage status, and try to make sure it is installed at the next OCaml(build) release.
